name: RhythmTap
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: "17.0"
targets:
  RhythmTap:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
        type: resource
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yourname.rhythmtap
      SWIFT_VERSION: 5.0
      INFOPLIST_FILE: Resources/Info.plist
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: "8KG73NCNM2"
    scheme:
      testTargets: []
